### ISSUE TITLE
KeyError: 'default' in _ValidateSettingsElement

### ISSUE THREAD

**Issue by LeonardoRick** [iterative/PyDrive2#108]
I'm receiveing the following error when calling `GoogleAuth()`
```bash
Traceback (most recent call last):
  File "/home/leonardo/.local/lib/python3.8/site-packages/pydrive2/settings.py", line 154, in _ValidateSettingsElement
    default = struct[key]["default"]
KeyError: 'default'
```

This is my code:
```python
from pydrive2.auth import GoogleAuth,
gauth = GoogleAuth()
...
```
And this is the line that throws the error:

```python
# settings.py _ValidateSettingsElement method line 156
default = struct[key]["default"]
...
```

I was able to see the dict with some logs:
```python
try:
    print('key:')
    print(key)
    print('dict:')
    print(struct[key])
    default = struct[key]["default"]
...
```

And found that the dict actually do not have 'default' key:
```bash
key:
client_id
dict:
{'type': <class 'str'>, 'required': True}
Traceback (most recent call last):
  File "/home/leonardo/.local/lib/python3.8/site-packages/pydrive2/settings.py", line 156, in _ValidateSettingsElement
    default = struct[key]["default"]
KeyError: 'default'
```

I was able to bypass the issue changing the line 156 with the following:

```python
default = struct[key]["default"] if 'default' in struct[key] else ''
```

But I don't know if this will give me trouble in the future.

Hope It helps to fix, thanks for such a great lib

**Comment by shcheklein** [comment]
@LeonardoRick do you have the `client_secrets.json` and/or `settings.yaml` as described here https://iterative.github.io/PyDrive2/docs/build/html/oauth.html ? Or do you rely on defaults? If you have them, could you please share the structure of the `client_secrets.json` (don't include values), and the settings file.

**Comment by LeonardoRick** [comment]
I'm sorry. I guess I made a mistake. I'm using a project that has both `client_secrets.json` and `settings.yaml`. I only checked `client.secrets` and settings.yaml was not fully defined. Thanks for your help.

This was my `settings.yaml` without client_id and client_secret:

```yaml
client_config_backend: settings
client_config:
  client_id:  # client_id
  client_secret: # client_secret

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive


```
