### ISSUE TITLE
PyDrive2 not saving credentials

### ISSUE THREAD

**Issue by mislavpericaxilis** [iterative/PyDrive2#153]
```yaml
client_config_backend: settings
client_config:
  client_id: id
  client_secret: secret

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope: 
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive.metadata
 ```
  
  in the root of my Django project, I'm placing the `client_secret.json` and `settings.yml`, however, `credentials.json` isn't getting created and saved after a successful login. 
  
![image](https://user-images.githubusercontent.com/92310671/144202735-1a4efd7d-67ef-4cca-8099-142bb60f57f0.png)

Current use of the library. 

```python
    gauth = GoogleAuth()
    gauth.LocalWebserverAuth()
    drive = GoogleDrive(gauth)
```
Issue is that upon each request, it requires to select an account which is not acceptable in this use case.
I'm using the entire thing with celery to run a tasks that uploads the file to a drive

**Comment by Alex-Nalin** [comment]
I have the same issue, not sure how to make it save the credentials and not ask again...

**Comment by mislavpericaxilis** [comment]
@Alex-Nalin Honestly I'd just avoid PyDrive2 and switch to something like S3 or Digital Ocean spaces. I ended up fixing it by pasting the creds file from the older project and using that...

**Comment by shcheklein** [comment]
@mislavpericaxilis :

I think `client_secret.json` is not needed if `settings` is set as `client_config_backend` and:

```yaml
client_config:
  client_id: id
  client_secret: secret
```

are set.

> Current use of the library.

Could you give more details? Where and how do you run it? 

It might something setup specific. E.g. celery runs it in a temp directory each time or something.

Could you create a toy example that does auth and then runs a few requests in a row?
