### ISSUE TITLE
Stuck on authenthicating

### ISSUE THREAD

**Issue by patricialorenzoc** [iterative/PyDrive2#177]
Hello, i'm trying to use PyDrive2 to link Kaggle to my Google Drive, i've followed the authenthication quickstart from the documentation but i'm stuck on authenthicating, i have a settings.yaml with the following code:

```yaml
client_config_backend: file
client_config_file: client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope: 
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive.readonly
```

I have both `client_secrets.json` and `credentials.json` created and i was trying to use the following code to download the contents of a folder:

```python
import os
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()
drive = GoogleDrive(gauth)


file_list = drive.ListFile( {'q': {secret_value_1} + " in parents"}).GetList()  

for f in file_list:
    print('title: %s, id: %s' % (f['title'], f['id']))
    fname = f['title']
    print('downloading to {}'.format(fname))
    f_ = drive.CreateFile({'id': f['id']})
    f_.GetContentFile(fname)
```

So i run this code and it gives me a link to open and authenthicate like this: 
![imagen](https://user-images.githubusercontent.com/22030624/169711466-c9b5c691-318b-4389-89b0-6ce88cb8dd92.png)

So i follow with the authenthication but instead of giving me an error or succeeding it gives me a listing of the contents of the folder and i don't know how to fix this.

I'm using pythons `http.server` to launch on ports `8080 `or `8090` as a local server. Is using this the problem?
