### ISSUE TITLE
Access token refresh failed: invalid_grant: Token has been expired or revoked.

### ISSUE THREAD

**Issue by meet1919** [iterative/PyDrive2#184]
This is the error I am getting `pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked`. Upon looking at a similar issue @shcheklein  mentioned that the error is not in pydrive2 but in `pygsheets`. I cant find similar issue in the `pygsheets`.

Below is my code:
```
gauth.LoadCredentialsFile("mycreds.txt")
if gauth.credentials is None:
    # Authenticate if they're not there
    gauth.LocalWebserverAuth()
elif gauth.access_token_expired:
    # Refresh them if expired
    gauth.Refresh()
else:
    # Initialize the saved creds
    gauth.Authorize()
# Save the current credentials to a file
gauth.SaveCredentialsFile("mycreds.txt")
```
The seems to work and refresh the token earlier but now it doesnt. Upon looking to the `auth.py` in `pydrive2` I found this:

```
if self.http is None:
    self.http = self._build_http()
try:
    self.credentials.refresh(self.http)
except AccessTokenRefreshError as error:
    raise RefreshError("Access token refresh failed: %s" % error)
```
The problem seems to arising at `self.credentials.refresh(self.http)`. I dont know what is `self.http` but the problem might be coming from `self._build_http()`. What should I do?

Below is the `settings.yaml`:
```
client_config_backend: settings
client_config:
  client_id: id
  client_secret: secret

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive.metadata
```
