### ISSUE TITLE
Refresh token not working

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [iterative/PyDrive2#367]
After multiple attempts i am running out of ideas.
I used the examples on the documentation and have the following

settings.yaml
```yaml
client_config_backend: file
client_config_file: client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
```

drive.py
```py
class GDrive:
    def __init__(self):
        self.drive: Optional[GoogleDrive] = None

    def _init_google_drive_auth(self):
        gauth = GoogleAuth()
        gauth.LocalWebserverAuth()
        self.drive = GoogleDrive(gauth)

    def _refresh(self):
        gauth = GoogleAuth()
        gauth.LoadCredentialsFile('../credentials.json')
        try:
            if gauth.credentials is None:
                gauth.LocalWebserverAuth()
            elif gauth.access_token_expired:
                gauth.Refresh()
            else:
                gauth.Authorize()
        except Exception as e:
            print(e)

        gauth.SaveCredentialsFile('../credentials.json')
        self.drive = GoogleDrive(gauth)
```

For some reason, after around 1 week i have the following error
```
An error message occurred: Access token refresh failed: invalid_grant: Bad Request
```

Note that I validated that my app is in Production on google cloud platform but the refresh token is not working.
